# Generated by Django 5.0.6 on 2024-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planted_trees', '0002_alter_plantedtree_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
