# Generated by Django 5.0.6 on 2024-06-22 12:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=2048)),
                ('scientific_name', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
                'db_table': 'trees',
                'ordering': ['-created_at'],
            },
        ),
    ]
